spring:
  kafka:
    bootstrap-servers: localhost:9091,localhost:9092,localhost:9093
    topic:
      input: input
      output: output
    group:
      tracker: tracker
      logging: logging
  datasource:
    url: jdbc:h2:mem:test
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
